spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://jianghaoyu.world:3306/sybida?characterencoding=utf-8&serverTimezone=UTC
    username: admin
    password: jianghaoyu-+0
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
# 配置别名包
mybatis:
  type-aliases-package: com.sy.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql